server:
  port: 8092
  servlet:
    context-path: /

spring:
  # 当 HTTP 状态码为 4xx 时直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
    # 解决PatternsRequestCondition.getPatterns()“ because “this.condition“ is null问题
    pathmatch:
      matching-strategy: ant_path_matcher
  #  关闭默认的静态资源路径映射
  web:
    resources:
      add-mappings: false
  redis:
    host: 192.168.56.102
    port: 6379
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jx_boot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    # 初始连接数
    initialSize: 5
    # 最小连接池数量
    minIdle: 10
    # 最大连接池数量
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置一个连接在池中最大生存的时间，单位是毫秒
    maxEvictableIdleTimeMillis: 900000
    # 配置检测连接是否有效
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    webStatFilter:
      enabled: true
    statViewServlet:
      enabled: true
      # 设置白名单，不填则允许所有访问
      allow:
      url-pattern: /druid/*
      # 控制台管理用户名和密码
      login-username: ruoyi
      login-password: 123456
    filter:
      stat:
        enabled: true
        # 慢SQL记录
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true

mybatis-plus:
  mapper-locations: classpath*:mapping/**/*Mapper.xml
  type-aliases-package: com.laolang.jx.**.entity
  global-config:
    db-config:
      id-type: auto
      select-strategy: not_empty
      insert-strategy: not_empty
      update-strategy: not_empty
      refresh-mapper: true
      db-type: mysql
      logic-delete-field: deleted
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: secret
  # 令牌有效期（默认30分钟）
  expireTime: 30

logging:
  config: classpath:log4j2-dev.xml

